name: Unit Tests

on:
  pull_request:
  workflow_dispatch:

# Cancel in-progress PR verification workflows
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2

    - name: Run Unit Tests
      shell: bash
      run: go test ./... -v
